enabled_locales: ["en", "ja"]
client:
  host: "localhost:3000"
user:
  name:
    max_length: 150
  email:
    max_length: 255
  password:
    min_length: 6
  size: 80
per_page: 10
accept_image: "image/jpeg,image/gif,image/png"
products:
  per_page: 9
