enabled_locales: ["en", "ja"]
client:
  host: "localhost:3000"
user:
  name:
    max_length: 150
  email:
    max_length: 255
  password:
    min_length: 6
  size: 80
category:
  max_length: 50
  min_length: 5
per_page: 10
accept_image: "image/jpeg,image/gif,image/png"
products:
  per_page: 9
  history_view: 9
  column_names:
    name: "Adidas"
    description: "From New York"
    quantity: 10
    price: 20
    category_id: 1
min_discount: 0
